import { CalendarEvent } from "./types";

// ===================== 샘플 이벤트 =====================
export const sampleEvents: CalendarEvent[] = [
    {
        id: 1,
        project_id: 101,
        title: "프로젝트 1 기획 회의",
        description: "DB 구조 및 API 명세서 확정 논의",
        start_at: "2025-09-24T10:00:00",
        end_at: "2025-09-24T11:30:00",
        all_day: false,
        visibility: 'PUBLIC',
        author_id: 1,
        location: "회의실 A",
        color: "bg-blue-500 text-white",
        project_name: "프로젝트 1",
    },
    {
        id: 2,
        project_id: 102,
        title: "여기 누르면 이벤트 내용이 나온다",
        description: "이벤트 상세 내용이 여기에 표시됩니다.",
        start_at: "2025-09-16T14:00:00",
        end_at: "2025-09-16T15:00:00",
        all_day: false,
        visibility: 'PUBLIC',
        author_id: 2,
        location: null,
        color: "bg-green-500 text-white",
    },
    {
        id: 3,
        project_id: 102,
        title: "여기 누르면 카드 모달로 보여",
        description: "모달 내용 확인용 개인 일정입니다.",
        start_at: "2025-09-16T16:00:00",
        end_at: "2025-09-16T16:30:00",
        all_day: false,
        visibility: 'PRIVATE',
        author_id: 1,
        location: "개인 좌석",
        color: "bg-yellow-400",
    },
];